spring:
  application:
    name: item-service
    
#server:
#  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    registry-fetch-interval-seconds: 90
  instance:
    lease-renewal-interval-in-seconds: 30

---
spring:
  profiles: item1

server:
  port: 8001
  
---
spring:
  profiles: item2

server:
  port: 8002  